#
# Since: January, 2021
# Author: gvenzl
# Name: Dockerfile.11202
# Description: Dockerfile to build Oracle DB XE 11.2.0.2.
#              The Dockerfile supports building different flavors of images.
#              These flavors can be controlled via the build argument "BUILD_MODE" which
#              supports three modes, as follows:
#
#    FULL:     No database functionality is removed, just log and trace files from the
#              database installation  itself.
#              Additional required packages, such as 'gcc' and 'make' are installed
#              (needed for native PL/SQL execution, etc.)
#              Database configuration is as per default installation, except for the
#              location of the fast_recovery_area and redo logs.
#
#    REGULAR:  Following functionalities have been removed:
#              * gcc & make (needed for native PL/SQL execution, etc.)
#              * APEX
#
#    SLIM:     Following functionalities have been removed:
#              * Everything that has been removed in the REGULAR image, plus:
#              * Oracle Text
#
# Copyright 2021 Gerald Venzl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM oraclelinux:8-slim

ARG BUILD_MODE

LABEL org.opencontainers.image.source https://github.com/gvenzl/oci-oracle-xe

ENV ORACLE_BASE=/u01/app/oracle \
    ORACLE_BASE_CONFIG=/u01/app/oracle/product/11.2.0/xe \
    ORACLE_BASE_HOME=/u01/app/oracle/product/11.2.0/xe \
    ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe \
    ORACLE_SID=XE \
    PATH=${PATH}:/u01/app/oracle/product/11.2.0/xe/bin:/u01/app/oracle \
    NLS_LANG=.AL32UTF8
    
COPY oracle-xe-11.2.0-1.0.x86_64.rpm xe.11202.rsp install.11202.sh container-entrypoint.sh resetPassword createAppUser healthcheck.sh /install/

RUN /install/install.11202.sh "${BUILD_MODE}"
    
USER oracle
WORKDIR ${ORACLE_BASE}

HEALTHCHECK CMD "${ORACLE_BASE}"/healthcheck.sh >/dev/null || exit 1

ENTRYPOINT ["container-entrypoint.sh"]