#!/usr/bin/env bash
# Variables used for the script
if [ ! -f `which pwgen` ]; then
  echo "You must have pwgen on your machine to run this script"
  exit 1
fi

CMG_COMMAND=docker
DKR_IMAGE="gvenzl/oracle-xe"
DKR_HOST_PORT=$1
DKR_CNT_NAME=$2
DKR_DATA_PATH=dbcxe-$DKR_CNT_NAME-dvol
DKR_ORA_USER_APP=DAAPPUSER
DKR_ORA_PW=`pwgen -1 16 | tr -d '\n'`
DKR_ORA_PW_APP=`pwgen -1 16 | tr -d '\n'`

echo "Docker Image ...............:'$DKR_IMAGE'"
echo "Docker User ................:'$DKR_ORA_USER_APP'"
echo "Docker Password ............:'$DKR_ORA_PW'"
echo "Docker Password (app) ......:'$DKR_ORA_PW_APP'"
echo "Docker Volume Name..........:'$DKR_DATA_PATH'"
echo "Docker Host Port ...........:'$DKR_HOST_PORT'"
echo "Docker Container Name ......:'$DKR_CNT_NAME'"


if [ -z "$DKR_HOST_PORT" ]; then
  echo "You must provide docker host port"
  exit 1
fi


if [ -z "$DKR_CNT_NAME" ]; then
  echo "You must provide container name"
  exit 1
fi

$CMG_COMMAND run --name $DKR_CNT_NAME \
  -p $DKR_HOST_PORT:1521 \
  -e "ORACLE_PASSWORD=$DKR_ORA_PW" \
  -e "APP_USER=$DKR_ORA_USER_APP" \
  -e "APP_USER_PASSWORD=$DKR_ORA_PW_APP" \
  -v $DKR_DATA_PATH:/opt/oracle/oradata \
  -d $DKR_IMAGE

echo "Waiting for container '$DKR_CNT_NAME' to start ... " 
sleep 10

echo "Oracle Container '$DKR_CNT_NAME' has been started on port '$DKR_HOST_PORT' with initial password '$DKR_ORA_PW'"
